### ISSUE TITLE
Where is Django?

### ISSUE THREAD

**Issue by asif17r** [bdsumon4u/api-assignment-laravel#1]
You should be marked negatively. You disrespected whole Django community.

**Comment by bdsumon4u** [comment]
I appreciate your opinion. But Django does **not** belong to our syllabus.
Our teacher has given the assignment of the framework **out of the syllabus**.
I've used the framework from **out of the syllabus**.

**Comment by asif17r** [comment]
No, I will give you 10 Tk. Redo the assignment with Django.

**Comment by bdsumon4u** [comment]
Sure. I'll definitely do that for 10 taka. But you'll have to pay in **advance**.

**Comment by asif17r** [comment]
Wow. But I don't want you to suffer. I have other task for you. After Eid In Sha Allah.
